### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tdowgielewicz** [avatsaev/angular4-docker-example#3]
Hi Just tried to build your example

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/app/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
The command '/bin/sh -c npm install   && ng build --aot --prod   && rm -rf /usr/share/nginx/html/*   && mv ./dist/* /usr/share/nginx/html/   && npm cache clean   && apk del nodejs libstdc++ libgcc libuv http-parser ca-certificates   && rm -rf ./*' returned a non-zero code: 1

OS. Ubuntu 16.04 (Virtual Box) 
Docker version 17.06.0-ce, build 02c1d87

**Comment by avatsaev** [comment]
I've fixed the issue but I suggest you use the docker file from this repo because it's more efficient and uses docker's multi stage builds: https://github.com/avatsaev/angular-contacts-app-example

here is the related article I wrote explaining how it works: https://medium.com/@avatsaev/create-efficient-angular-docker-images-with-multi-stage-builds-907e2be3008d

**Comment by tdowgielewicz** [comment]
Thank you
